{% set name = "rhizopus" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jwergieluk/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 707daf32859de7d4934013e254377229d0453f48e894640ef228e29a65912cfa

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - rhizopus
    - rhizopus.broker
    - rhizopus.broker_observer
    - rhizopus.broker_simulator
    - rhizopus.orders
    - rhizopus.price_graph
    - rhizopus.primitives
    - rhizopus.series_recorder
    - rhizopus.strategy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jwergieluk/rhizopus
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: 'Trading simulator'
  description: |
    rhizopus is a Python trading simulation framework and a backtesting tool.
    It can be used to construct broker simulators for backtesting with
    historical data, as well as for live trading. Its main goal is to provide a
    simple unified interface for both backtesting and live trading.
  doc_url: https://github.com/jwergieluk/rhizopus
  dev_url: https://github.com/jwergieluk/rhizopus

extra:
  recipe-maintainers:
    - jwergieluk
    - shackmann
